packages:
  - packages/*

catalog:
  '@knime/kds-components': 0.5.9
  '@knime/kds-styles': 0.5.9
  vue: 3.5.18

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@knime/*'

overrides:
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  markdown-it@>=13.0.0 <14.1.1: '>=14.1.1'
  # Upgrade ajv to 8.18.0+ for production deps (fixes security vulnerability)
  # But exclude ESLint packages which need ajv 6.x
  ajv@>=8.0.0 <8.18.0: '>=8.18.0'
