packages:
  - packages/*

catalog:
  '@knime/kds-components': 0.4.0
  '@knime/kds-styles': 0.4.0
  vue: 3.5.18

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@knime/*'

overrides:
  knime-ui-table: link:../../../../Library/pnpm/global/5/node_modules/@knime/knime-ui-table
