module.exports = {
  preset: "ts-jest",
  testEnvironment: "jsdom",
  moduleFileExtensions: ["js", "ts", "json", "mjs"],
  roots: ["<rootDir>"],
  modulePaths: ["<rootDir>"],
  transform: {
    "\\.js$": "babel-jest",
    "\\.mjs$": "babel-jest",
    "^.+\\.tsx?$": [
      "ts-jest",
      {
        tsconfig: "tsconfig.vitest.json",
      },
    ],
    "\\.(css|styl|less|sass|scss|ttf|woff|woff2)(\\?|$)": "jest-transform-stub",
    // '\\.svg': '<rootDir>/test/unit/jest-transform-svgs',
    // '\\.(jpg|webp)': '<rootDir>/test/unit/jest-file-loader',
  },
  transformIgnorePatterns: ["/node_modules/?!(@knime/ui-extension-service)"],
  moduleNameMapper: {
    "\\.(jpg|png)\\?(jpg|webp)": "<rootDir>/test/unit/assets/stub.$2",
    "^@/(.*\\.svg)\\?inline$": "<rootDir>/src/$1",
    "^~/(.*\\.svg)\\?inline$": "<rootDir>/$1",
    "^(.*\\.svg)\\?inline$": "$1",
    "^(.*\\.svg)\\?url$": "<rootDir>/test/unit/assets/svg_url_stub",
    "^(.*\\.svg)\\?raw$": "<rootDir>/test/unit/assets/svg_raw_stub",
    // '\\.svg\\?data$': '<rootDir>/test/unit/assets/stub.data',
    "^vue$": "vue/dist/vue.common.js",
    "^@/(.*)$": "<rootDir>/src/$1",
    "^~/(.*)$": "<rootDir>/$1",
  },
  reporters: ["default", ["jest-junit", { outputDirectory: "./coverage" }]],
  coverageReporters: ["lcov", "text"],
  // keep in sync with sonar-project.properties!
  collectCoverageFrom: [
    "<rootDir>/**/*.(js|ts)",
    "!config.js",
    "!**/*.config.js",
    "!.eslintrc*.js",
    "!**/.eslintrc*.js",
    "!<rootDir>/test/unit/test-util",
    "!<rootDir>/src/vite-env.d.ts",
    "!<rootDir>/src/viteNoESmodulesPlugin.ts",
    "!<rootDir>/vite.config.ts",
    "!<rootDir>/vite-env.d.ts",
    "!<rootDir>/.stylelintrc.js",
  ],
  coveragePathIgnorePatterns: [
    "^<rootDir>/(coverage|dist|test|target|node_modules|bin|src/dev)/",
    "^<rootDir>/src/(main.ts|dev.ts)",
  ],
  watchPathIgnorePatterns: [
    "^<rootDir>/(coverage|dist|target|node_modules|bin)/",
  ],
  testEnvironmentOptions: { url: "http://test.example/" },
  testMatch: ["<rootDir>/test/unit/suites/**/*.test.ts"],
  // watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
  setupFiles: ["<rootDir>/test/unit/jest-setup"],
};
